sudo: required

os: linux
language: rust
rust:
  - stable
cache:
  - cargo
  - apt
addons:
  apt:
    packages:
      - binutils-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

script:
- cargo build
#- cargo test -- --nocapture
- cargo install cargo-kcov
- cargo kcov --print-install-kcov-sh | sh
- sh beep & cargo kcov --verbose --lib --coveralls
- bash <(curl -s https://codecov.io/bash)